language: java

script:
    - cd SIGET
    - mvn compile
    
deploy:
  provider: heroku
  api_key:
    secure: "tvJJq6Z+s7ehg3n+M36aIN3lZeahhA4t+wK4VVDKfxnTgYfhdTk2Ad+fKSjqqW7MXL1efGSjl7kpol9sCITIMZaXw84GaGFR+JI1qPNSWanIkqaUJLs19IPAqCivudTSBAMimgoz5cFsFoeeeNRWkj3t3luHEU69mBpvb6U8v4zjQQhqzAjLhDvHsVRhiq+iK/jMBQ7lNcU/Gzwz2Dal2S+cdUy8U+uT1hXips3JrOv0fPIZjTpkvQRoIXOwF+ynSJm1rR+ees2F+9iJwZtW4CpvMQCTJTKV5b9RjOkH4madNhc3nvBwWS70wtYkLeQUqSc5InDu/r54usYQ2l+dDc1qNPG+Om0Hcxk4+/IrVW+V/3mJU9cPLBoLqSfQkFLG74lU3aTvLp67ZLVMnv8K2YumVhmgSWF4UXD4LNshvTeOidJRu1FampuBL3m46x/akU8FxFarmzXt71UQ3+iS6LB+3WB6GrC5NqZwMzGlZrAF9uu1qoTxwWa00BOvhW3PZpoJU2XLpZUNY81MsQJpLYkNgJ6xBx0i9y5vHziEJ+or3Yvrf4IE5W//K4/5mC02zaAkUeVnLI/PEUjXQN0qpjrEZy7r0CC2uLKh6ozPYsYamcqQrE+ZKg1falZuuWGFN8bysJMba+xxArX76s3aNpnx/kf/qZq5LR6sMtHTkuo="
    app: siget-equipo3
  on: 
    branch: develop