language: java
script:
- cd SIGET
- mvn compile
deploy:
  provider: heroku
  api_key:
    secure: 0TQAQFc0C5yvv5V/5m4oiNJi7JQKVLhxNYdWxqg10GZSuBhlfb1StoxBRIx2Yww7rCSQcc4EhCGFyqjU0RkeW5WaoGBlaBRQKc8Ki9B20mB0gsYj2vFObDc4oP73h8+C8eos9gvgLu3zn2x0iwlFT8A9e4GWyh0+bynOXKRgbzu6Fmulb/IKtIQBl9EZwzg8ds9MI1AMdUzalR+1u29RPnj2qPs2IBZwKH3d/hBCIALbnKy3dg4S/8O5C17HZcP5Y09/ZDgjfOtpoi/YHJAyIeBOtQn39Ip/NLrxmDkl2aEEdJ6H2wGf+R4IOOz7kkdvIB3+UzyLjEi3YXL5IJZM4s0l2Fu9WLqB5czMqMm99HrVrOd/9jUiyUQL5ZvPc6XJwiO1fWCzkcH83hhAts7bFn3BESS5qserYQmHWXx2hHHL0pwreDJYVbR8jM44qdc5SJAw/+2tFJQhSVpyHmWtIKyHHfMa4WVgQbQrtRuOIDp9UYSGM3G+xgw5fTGFdgC1bJXSL8q996zbCVto/XUrm8icos7Dw6qnGNcp8hz7cJ4mG2ZwWLbZQU4P4Z8qtOYbJm1cU+r3ooqeslHsGcVbUZFdpV1GDiUr09Cu3Yh5qWh41QtP3MbeBpOKbf6xa/kWocWJR628c01wn/VFYWvHgVNyzyXU+knJoagB1TCwZTw=
  on:
    branch: develop
